version: "3.8"

volumes:
  apt-cache: {}
  history: {}
  app-deps: {}
  app-build: {}
  app-elixir-ls: {}
  app-asdf: {}
  app-storage: {}

services:
  app:
    environment:
      LOGGER_LEVEL: 1
      HISTFILE: /var/tmp/history/shell.history
      GIT_AUTHOR_EMAIL:
      GIT_COMMITTER_EMAIL:
      GITHUB_TOKEN:
      PORT: 400
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
      args:
        HEX_API_KEY:
        GITHUB_TOKEN:

    volumes:
      - ..:/workspace:cached
      - "apt-cache:/var/cache/apt:rw"
      - "history:/var/tmp/history:rw"
      - "app-asdf:/home/vscode/.asdf:rw"
      - "app-deps:/workspace/deps:rw"
      - "app-build:/workspace/_build:rw"
      - "app-elixir-ls:/workspace/.elixir_ls:rw"
      - "app-storage:/storage:rw"

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
